### ISSUE TITLE
Overview: Number sequences over time

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboard-components#315]
Let's create a component that shows the absolute number of sequences over time. It is very similar to #3 which shows the relative number.

## Tasks

- [ ] Number sequences over time: bar chart
- [ ] Number sequences over time: line chart
- [ ] Number sequences over time: Data table
